### ISSUE TITLE
Exporting tasks breaks with Project "__getstate__" field is not set

### ISSUE THREAD

**Issue by aurelien-m** [heartexlabs/label-studio-sdk#72]
I'm trying to export tasks from a project with:
```python
ls_project.export_tasks(export_type='JSON')
```

However, I get this error:
```
Traceback (most recent call last):
  File "/tmp/tmpf1fo3h4f.py", line 47, in <module>
    task.upload_artifact(
  File "/home/user/Projects/aienv/lib/python3.10/site-packages/clearml/task.py", line 1949, in upload_artifact
    return self._artifacts_manager.upload_artifact(
  File "/home/user/Projects/aienv/lib/python3.10/site-packages/clearml/binding/artifacts.py", line 744, in upload_artifact
    pickle.dump(artifact_object, f)
  File "/home/user/Projects/aienv/lib/python3.10/site-packages/label_studio_sdk/project.py", line 107, in __getattr__
    return self._get_param(item)
  File "/home/user/Projects/aienv/lib/python3.10/site-packages/label_studio_sdk/project.py", line 259, in _get_param
    raise LabelStudioAttributeError(f'Project "{param_name}" field is not set')
label_studio_sdk.project.LabelStudioAttributeError: Project "__getstate__" field is not set
```

Any ideas?

**Comment by aurelien-m** [comment]
Never mind, it's actually an issue I have with ClearML, sorry!
